### ISSUE TITLE
Sudden code issue with GUI

### ISSUE THREAD

**Issue by afowxc** [joeweiss/birdnetlib#103]
Hello,
I've been using BirdNET to run classifiers for months now as I work though building some custom models. My computer restarted, and now when I try to open the GUI (using python3 py.gui like usual), it brings up error lines in the codes including 
Traceback (most recent call last):
  File "/Users/me/BirdNET-Analyzer/gui.py", line 969, in <module>
    build_single_analysis_tab()
  File "/Users/me/BirdNET-Analyzer/gui.py", line 717, in build_single_analysis_tab
    ) = species_lists(False)
  File "/Users/me/BirdNET-Analyzer/gui.py", line 655, in species_lists
    species_file_input = gr.File(file_types=[".txt"], info="Path to species list file or folder.", visible=False)
  File "/Users/me/anaconda3/envs/birdnet-analyzer/lib/python3.10/site-packages/gradio/component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: File.__init__() got an unexpected keyword argument 'info'

Have there been updates? Why would this all of a sudden have issues?

Thanks in advance.

**Comment by joeweiss** [comment]
Hi @afowxc.

The GUI is part of the larger [BirdNET-Analyzer](https://github.com/kahst/BirdNET-Analyzer/) project. I would suggest raising an issue over at their repo's [issues](https://github.com/kahst/BirdNET-Analyzer/issues).

This repo (`birdnetlib`) is the Python library for BirdNET analyzers.
